#ifndef BATTERY_CHECK_HPP
#define BATTERY_CHECK_HPP

enum BatteryStatus {
    NORMAL,
    LOW_SOC_BREACH,
    LOW_SOC_WARNING,
    HIGH_SOC_WARNING,
    HIGH_SOC_BREACH,
    LOW_TEMP_BREACH,
    HIGH_TEMP_BREACH,
    CHARGE_RATE_BREACH
};

#endif // BATTERY_CHECK_HPP
